### ISSUE TITLE
Cannot compile test suite with ComputeCPP

### ISSUE THREAD

**Issue by a-doumoulakis** [KhronosGroup/SyclParallelSTL#26]
For the last couple of week I've been trying with @keryell to make triSYCL work with the SyclParallelSTL tests and benchmarks. The [branch](https://github.com/a-doumoulakis/SyclParallelSTL/tree/triSYCL "triSYCL Branch") that contains the changes made to SyclParallelSTL now compiles and runs every test and benchmark with triSYCL. But before creating a pull request, I had to check if it still worked with ComputeCPP.

The issue is that I cannot compile the parallel STL tests with ComputeCPP, when I attempt to do so I get a series of :  
```
undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)' 
```
This happens with the triSYCL branch as well as with the master branch.

I am compiling with gcc 6.2 on ubuntu 16.10 and computeCPP CE 0.1.3.

**Comment by keryell** [comment]
Can you try with latest ComputeCpp instead?

**Comment by Zakor94** [comment]
I can confirm I have the same issue with ComputeCPP CE 0.2.0 on Ubuntu 16.04 and gcc 6.3.

**Comment by Ruyk** [comment]
Is this using the ComputeCpp package for Ubuntu 16.04 ? If that's the case I'll re-direct this question to the ComputeCpp support team...

**Comment by Zakor94** [comment]
Yes I am using the ubuntu package from the codeplay website.

**Comment by Zakor94** [comment]
I went back to Ubuntu 14.04.4 with gcc 4.8 and it works fine.
It's good enough for me :)

**Comment by Ruyk** [comment]
@Zakor94  did you manage to get parallel STL working on Ubuntu 16.04 at all?

**Comment by Zakor94** [comment]
@Ruyk I am still working on Ubuntu 14.04. I had issues installing the amd driver pro driver on Ubuntu 16.04 (unrelated to ComputeCpp). I read it could be because my 16.04 is an upgrade from 14.04 but I haven't looked more into it :/

**Comment by keryell** [comment]
I guess this issue is now obsolete with Ubuntu 17.10 and ComputeCpp 0.5
